knowescape/urls.py
from . import views
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index, name="home"),
    path('start-up', views.start_up, name="start-up"),
    path('contact', views.contact, name="contact"),
    path('signup/learner', views.learner_signup, name="learner-signup"),
    path('signup/company', views.company_signup, name="company-signup"),
    path('enterprise-supplier-dev', views.es_dev, name="es-dev"),
    path('skills-dev', views.skills_dev, name="skills-dev"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projectknowescape/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('knowescape.urls')),
]

urlpatterns += staticfiles_urlpatterns()

knowescape/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


# Create your models here.
class Applicants(models.Model):
    DISABILITY_CHOICES = (
        ("yes", "Yes"),
        ("no", "No")
    )

    first_names = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    birth_date = models.DateField()
    home_address = models.TextField()
    email = models.EmailField(unique=True)
    phone_number = PhoneNumberField(region="ZA")
    disability = models.CharField(max_length=3, choices=DISABILITY_CHOICES)
    disability_note = models.FileField(upload_to='disability_notes/', blank=True, null=True)
    certified_id = models.FileField(upload_to='certified_ids/')
    matric_certificate = models.FileField(upload_to='matric_certificates/', blank=True, null=True)

    def __str__(self):
        return f"{self.first_names} {self.last_name}"


class Companies(models.Model):

    smme_name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    cipc_reg = models.IntegerField()
    operating_years = models.IntegerField()
    sars_compliance = models.CharField(max_length=100)
    cipc_docs = models.FileField(upload_to='CIPC_docs/', blank=True, null=True)
    company_profile = models.FileField(upload_to='Company_profile/', blank=True, null=True)
    bbbee_cert = models.FileField(upload_to='BBBEE_certificates/', blank=True, null=True)

    def __str__(self):
        return f"{self.smme_name}"

knowescape/forms.py
from django import forms
from django.core.exceptions import ValidationError
from phonenumber_field.formfields import PhoneNumberField


class ContactForm(forms.Form):

    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    company = forms.CharField(required=False)
    message = forms.CharField(widget=forms.Textarea, required=True)


class LearnerForm(forms.Form):

    disability_choices = (
        ("yes", "yes"),
        ("no", "no")
    )

    first_names = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label="Date of Birth"
    )
    home_address = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    phone_number = PhoneNumberField(required=True, region="ZA")
    disability = forms.ChoiceField(required=True, choices=disability_choices)
    disability_note = forms.FileField(required=False)
    certified_id = forms.FileField(required=True)
    matric_certificate = forms.FileField(required=False)


class CompanyForm(forms.Form):

    smme_name = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    cipc_reg = forms.IntegerField(required=True)
    operating_years = forms.IntegerField(required=True)
    sars_compliance = forms.CharField(required=True)
    cipc_docs = forms.FileField(required=True)
    company_profile = forms.FileField(required=True)
    bbbee_cert = forms.FileField(required=True)

    # def clean_disability_note(self):
    #     file = self.cleaned_data.get('disability_note')
    #     if file and not file.name.endswith(('.pdf', '.jpg', '.jpeg', '.png')):
    #         raise ValidationError("Only PDF, JPG, and PNG files are allowed for the doctor's note.")
    #     return file

    # def clean_certified_id(self):
    #     file = self.cleaned_data.get('certified_id')
    #     if file and not file.name.endswith(('.pdf', '.jpg', '.jpeg', '.png')):
    #         raise ValidationError("Only PDF, JPG, and PNG files are allowed for the certified ID.")
    #     return file

    # def clean_matric_certificate(self):
    #     file = self.cleaned_data.get('matric_certificate')
    #     if file and not file.name.endswith(('.pdf', '.jpg', '.jpeg', '.png')):
    #         raise ValidationError("Only PDF, JPG, and PNG files are allowed for the matric certificate.")
    #     return file

knowescape/views.py
from django.contrib import messages
from django.http import HttpResponse
from .models import Applicants, Companies
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError
from .forms import ContactForm, LearnerForm, CompanyForm


def index(request):

    context = {
        'page_title': 'Business & Skills Development'
    }

    return render(request, "knowescape/index.html", context)


def contact(request):

    if request.method == "POST":
        form = ContactForm(request.POST)
        sender = request.META.get('HTTP_REFERER')

        if form.is_valid():
            sender_first = request.POST['first_name']
            sender_last = request.POST['last_name']
            sender_email = request.POST['email']
            company = request.POST['company']
            sender_message = request.POST['message']

            try:
                send_mail(
                    f'Inquiry by {sender_first} {sender_last}',
                    sender_message,
                    sender_email,
                    ['rhulanimogotsi@gmail.com', 'info@knowescape.co.za']
                )

                messages.success(request, 'Message sent! Expect to hear from us soon!')
                return redirect('home')
            except BadHeaderError:
                return HttpResponse('Invalid Header')
    else:
        form = ContactForm()

    context = {
        'ContactForm': form,
        'page_title': 'Reach Out'
    }

    return redirect(sender)


def start_up(request):

    context = {
        'page_title': 'Start-Up Support'
    }

    return render(request, "knowescape/start-up.html", context)


def es_dev(request):

    context = {
        'page_title': 'Enterprise & Supplier Development'
    }

    return render(request, "knowescape/es-dev.html", context)


def skills_dev(request):

    context = {
        'page_title': 'Skills Development'
    }

    return render(request, "knowescape/skills-dev.html", context)


def learner_signup(request):
    if request.method == "POST":
        form = LearnerForm(request.POST, request.FILES)

        if form.is_valid():
            # Check for unique email
            email_address = form.cleaned_data['email']
            if Applicants.objects.filter(email=email_address).exists():
                messages.error(request, "This e-mail is already in use.")
            else:
                # Retrieve data from form
                first_names = form.cleaned_data['first_names']
                last_name = form.cleaned_data['last_name']
                birth_date = form.cleaned_data['birth_date']
                home_address = form.cleaned_data['home_address']
                phone_number = form.cleaned_data['phone_number']
                disability = form.cleaned_data['disability']
                disability_note = form.cleaned_data.get('disability_note')
                certified_id = form.cleaned_data['certified_id']
                matric_certificate = form.cleaned_data.get('matric_certificate')

                # Save applicant to the database
                applicant = Applicants.objects.create(
                    first_names=first_names,
                    last_name=last_name,
                    birth_date=birth_date,
                    home_address=home_address,
                    email=email_address,
                    phone_number=phone_number,
                    disability=disability,
                    disability_note=disability_note,
                    certified_id=certified_id,
                    matric_certificate=matric_certificate
                )

                # Send email confirmation
                try:
                    send_mail(
                        'Skills Development Application',
                        f"""
                        First Names: {first_names}
                        Last Name: {last_name}
                        Date of Birth: {birth_date}
                        Home Address: {home_address}
                        Email Address: {email_address}
                        Disability: {disability}
                        """,
                        email_address,
                        ['rhulanimogotsi@gmail.com', 'info@knowescape.co.za']
                    )
                    messages.success(request, 'Application Received! Check your emails for confirmation!')
                    return redirect('home')
                except BadHeaderError:
                    return HttpResponse('Invalid Header')
        else:
            messages.error(request, form.errors.as_text())
    else:
        form = LearnerForm()

    context = {
        'LearnerForm': form,
        'page_title': 'Skills Development'
    }

    return render(request, "knowescape/learner-signup.html", context)


def company_signup(request):
    if request.method == "POST":
        form = CompanyForm(request.POST, request.FILES)
        
        if form.is_valid():
            # Validate unique email
            email = form.cleaned_data['email']
            if Companies.objects.filter(email=email).exists():
                form.add_error('email', 'This email is already registered.')
            else:
                # Retrieve data from the form
                smme_name = form.cleaned_data['smme_name']
                cipc_reg = form.cleaned_data['cipc_reg']
                operating_years = form.cleaned_data['operating_years']
                sars_compliance = form.cleaned_data['sars_compliance']
                cipc_docs = form.cleaned_data['cipc_docs']
                company_profile = form.cleaned_data['company_profile']
                bbbee_cert = form.cleaned_data['bbbee_cert']
                
                # Save company to the database
                company = Companies.objects.create(
                    smme_name=smme_name,
                    email=email,
                    cipc_reg=cipc_reg,
                    operating_years=operating_years,
                    sars_compliance=sars_compliance,
                    cipc_docs=cipc_docs,
                    company_profile=company_profile,
                    bbbee_cert=bbbee_cert
                )
                
                # Send email confirmation (optional)
                try:
                    send_mail(
                        'Company Registration Confirmation',
                        f"""
                        Thank you for registering with us!
                        Company Name: {smme_name}
                        CIPC Registration: {cipc_reg}
                        Operating Years: {operating_years}
                        SARS Compliance: {sars_compliance}
                        """,
                        ['rhulanimogotsi@gmail.com', 'info@knowescape.co.za']
                    )
                    messages.success(request, 'Registration successful! Check your email for confirmation.')
                    return redirect('home')
                except BadHeaderError:
                    return HttpResponse('Invalid header found in the email.')
        else:
            messages.error(request, form.errors.as_text())    
    else:
        form = CompanyForm()

    context = {
        'CompanyForm': form,
        'page_title': 'Company Registration'
    }

    return render(request, "knowescape/company-signup.html", context)

knowescape/templates/knowescape/footer.html
{% load static %}

<section id="footer">
        <svg id="bg" width="1600" height="693" viewBox="0 0 1600 693" fill="none" xmlns="http://www.w3.org/2000/svg">
        <g opacity="0.42" filter="url(#filter0_f_218_19)">
        <path d="M0 319.759C129.008 184.036 302.518 570.386 550.034 319.759C797.549 69.1322 1107.57 732.329 1600.1 319.759C2092.63 -92.811 1600.1 693 1600.1 693H0V319.759Z" fill="url(#paint0_linear_218_19)" fill-opacity="0.59"/>
        </g>
        <defs>
        <filter id="filter0_f_218_19" x="-200" y="0" width="2219" height="893" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
        <feFlood flood-opacity="0" result="BackgroundImageFix"/>
        <feBlend mode="normal" in="SourceGraphic" in2="BackgroundImageFix" result="shape"/>
        <feGaussianBlur stdDeviation="100" result="effect1_foregroundBlur_218_19"/>
        </filter>
        <linearGradient id="paint0_linear_218_19" x1="800.048" y1="319.759" x2="800.048" y2="693" gradientUnits="userSpaceOnUse">
        <stop stop-color="#E66901"/>
        <stop offset="1" stop-color="#A34A00"/>
        </linearGradient>
        </defs>
        </svg>
        <div class="container-fluid footer-container">
            <a href="/" class="footer-brand">
                <img src="{% static 'knowescape/brand/logo - transparent - glow.png' %}">
            </a>
            <div class="footer-links">
                <div>
                    <ul class="footer-column">
                        <h5>Get Around</h5>
    
                        <li>
                            <a href="{% url 'home' %}">Home</a>
                        </li>
                        <li>
                            <a href="#cta">About Us</a>
                        </li>
                        <li>
                            <a href="#services">Our Services</a>
                        </li>
                        <li>
                            <a href="#services">Our Faculty</a>
                        </li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                    <ul class="footer-column">
                        <h5>Our Services</h5>
                        <li>
                            <a href="{% url 'start-up' %}">Start-Up Support</a>
                        </li>
                        <li>
                            <a href="{% url 'skills-dev' %}">Skills Development</a>
                        </li>
                        <li>
                            <a href="{% url 'es-dev' %}">Enterprise & Supplier Development</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <ul class="footer-column">
                        <h5>Contact</h5>
    
                        <li>
                            +27 82 703 4852
                        </li>
                        <li>
                            info@knowescape.co.za
                        </li>
                    </ul>
                    <ul class="footer-column">
                        <h5>Physical Address</h5>
                        <li>
                            Skybound Office Park
                        </li>
                        <li>
                            314 Consult Street
                        </li>
                        <li>
                            Rosebank, 2196
                        </li>
                        <li>
                            Johannesburg, Gauteng
                        </li>
                    </ul>
                </div>
            </div>
            <hr class="footer-divider">
            <div class="copyrights">
                <p class="copyright">© KnowEscape Consulting <span class="footer-date"></span>. All Rights Reserved</p>
                <p class="developer-credit">
                    Designed and Developed by  
                    <span>
                        <a href="https://linkedin.com/in/rhulanimogotsi">WinterTheDev</a>
                    </span>
                </p>
                <ul class="social-links">
                    <li>
                        <a href="{% url 'start-up' %}">
                            <ion-icon name="logo-facebook"></ion-icon>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'start-up' %}">
                            <ion-icon name="logo-twitter"></ion-icon>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'start-up' %}">
                            <ion-icon name="logo-linkedin"></ion-icon>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </section>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const footerDate = document.querySelector('.footer-date');
            
            if (footerDate) {
                const currentYear = new Date().getFullYear();
                footerDate.innerHTML = currentYear;
            }
        });
    </script>

knowescape/templates/knowescape/learner-signup.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <meta name="KnowEscape Consulting"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="KnowEscape">
    <meta name="robots" content="index, follow">
    <meta name="language" content="english">
    <meta name="description" content="Empowerment through Skills Development, Enterprise and Supplier Development, and Start-Up Support">

    <meta property="og:title" content="Skills and Business Development">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://knowescape.com">
    <meta property="og:image" content="{% static 'knowescape/images/website-box-bg.jpg' %}">
    <meta property="og:description" content="empowering individuals and organizations through comprehensive consultancy and training services.">
    <meta property="og:locale" content="en_ZA">
    <meta property="og:site_name" content="KnowEscape">

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lexend:wght@100..900&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree:ital,wght@0,300..900;1,300..900&display=swap" rel="stylesheet">

    <!-- CDNs -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <!-- imports -->
    <link rel="icon" type="image/x-icon" href="{% static 'knowescape/brand/favicon.png' %}">

    
    <link rel="stylesheet" href="{% static 'knowescape/signup.css' %}">
    <link rel="stylesheet" href="{% static 'knowescape/animations.css' %}">

    <title>{{page_title}} - KnowEscape</title>
</head>
<body>
    <nav>
        <a href="/" class="nav-brand">
            <img src="{% static 'knowescape/brand/nav-logo.png' %}">
        </a>
        <ul class="nav-list">
            <li class="nav-item">
                <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'home' %}#services" class="nav-link">Our Services</a>
                <ul class="sub-nav-list">
                    <li class="nav-item">
                        <a href="{% url 'start-up' %}" class="nav-link">Start-Up Support</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'skills-dev' %}" class="nav-link">Skills Development</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'es-dev' %}" class="nav-link">Enterprise & Supplier Development</a>
                    </li>
                </ul>
            </li>
            <li class="nav-item">
                <a href="{% url 'contact' %}" class="nav-link">Contact</a>
            </li>
            <li class="nav-item nav-action">
                <a href="" class="nav-link">Apply</a>
                <ul class="sub-nav-list sub-enroll">
                    <li class="nav-item">
                        <a href="{% url 'company-signup' %}" class="nav-link">As a business</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'learner-signup' %}" class="nav-link">As an individual</a>
                    </li>
                </ul>
            </li>
        </ul>
        <button type="button" class="nav-menu" data-bs-toggle="modal" data-bs-target="#offcanvas-nav">
            <span class="material-symbols-outlined">
                menu
            </span>
        </button>
        <div class="modal fade" id="offcanvas-nav" tabindex="-1" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <img src="{% static 'knowescape/brand/nav-logo.png' %}">
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        </button>
                    </div>
                    <div class="modal-body">
                        <ul class="main-nav">
                            <li class="nav-item">
                                <a href="{% url 'home' %}" class="nav-link">Home</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'home' %}#services" class="nav-link has-menu">Our Services</a>
                                <ul class="sub-nav-list no-display">
                                    <li class="nav-item sub-nav-item">
                                        <a href="{% url 'start-up' %}" class="nav-link">Start-Up Support</a>
                                    </li>
                                    <li class="nav-item sub-nav-item">
                                        <a href="{% url 'skills-dev' %}" class="nav-link">Skills Development</a>
                                    </li>
                                    <li class="nav-item sub-nav-item">
                                        <a href="{% url 'es-dev' %}" class="nav-link">Enterprise & Supplier Development</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'contact' %}" class="nav-link">Contact</a>
                            </li>
                        </ul>
                    </div>
                    <div class="modal-footer">
                        <a href="#" class="action-link site-btn">Apply</a>
                        <ul class="sub-nav-list no-display">
                            <li class="nav-item sub-nav-item">
                                <a href="{% url 'learner-signup' %}" class="nav-link">As an individual</a>
                            </li>
                            <li class="nav-item  sub-nav-item">
                                <a href="{% url 'company-signup' %}" class="nav-link">As an Enterprise</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <section id="contact">
        <div class="container-fluid contact-container">
            <div class="contact-header">
                <h1>
                    <span>Skills Development</span><br>
                    Application
                </h1>
            </div>
            <div class="contact-content">
                <form method="POST" enctype="multipart/form-data" id="contact-form">
                    {% csrf_token %}
                    <div class="form-block">
                        <label for="id_first_names">First names (As written in your ID):</label>
                        <input type="text" name="first_names" required id="id_first_names">
                    </div>
                    
                    <div class="form-block">
                        <label for="id_last_name">Last name:</label>
                        <input type="text" name="last_name" required id="id_last_name">
                    </div>

                    <div class="form-block">
                        <label for="id_birth_date">Date of Birth:</label>
                        <input type="date" name="birth_date" required id="id_birth_date">
                    </div>

                    <div class="form-block">
                        <label for="id_home_address">Home Address:</label>
                        <input type="text" name="home_address" id="id_home_address" required>
                    </div>
                    
                    <div class="form-block">
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" maxlength="320" required id="id_email">
                    </div>
                    
                    <div class="form-block">
                        <label for="id_phone_number">Phone Number:</label>
                        <input id="id_phone_number" type="tel" name="phone_number" required="">
                    </div>
                    <div class="form-block">
                        <label for="id_disability">Disability:</label>
                        <select name="disability" id="id_disability" required>
                            <option value="no">no</option>
                            <option value="yes">yes</option>
                        </select>
                    </div>
                    <div class="form-block">
                        <label for="id_disability_note">Medical Note (If living with Disability:)</label>
                        <input id="id_disability_note" type="file" name="disability_note" accept=".pdf, .docx, .jpg, .jpeg, .png">
                    </div>
                    <div class="form-block">
                        <label for="id_matric_certificate">Matric Certificate<br></label>
                        <input id="id_matric_certificate" type="file" name="matric_certificate" accept=".pdf, .docx, .jpg, .jpeg, .png">
                    </div>
                    <div class="form-block">
                        <label for="id_certified_id">Certified ID Copy</label>
                        <input id="id_certified_id" type="file" name="certified_id" required accept=".pdf, .docx, .jpg, .jpeg, .png">
                    </div>
                    <button type="submit">Send Application</button>                         
                </form>
            </div>
        </div>
    </section>
    {% if messages %}
    <ul class="messages animate__animated animate__slideInUp">
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script>

        // Select the element with the .has-menu class
        const menuElement = document.querySelector('.has-menu');

        // Add the click event listener to toggle the .no-display class when the menu element is clicked
        menuElement.addEventListener('click', function(event) {
            var subNav = document.querySelector('.modal-content .sub-nav-list');

            // Toggle the .no-display class
            subNav.classList.toggle('no-display');

            // If the .no-display class is removed (meaning the element is displayed), listen for clicks outside the targetElement
            if (!subNav.classList.contains('no-display')) {
                document.addEventListener('click', outsideClickListener);
            }
        });

        // Function to check for clicks outside the target element
        function outsideClickListener(event) {
            const subNav = document.querySelector('.modal-content .sub-nav-list');
            
            // Check if the click happened outside the targetElement and the menuElement
            if (!subNav.contains(event.target) && !menuElement.contains(event.target)) {
                // Add the .no-display class back
                subNav.classList.add('no-display');
                
                // Remove this event listener after the .no-display class is added
                document.removeEventListener('click', outsideClickListener);
            }
        }

        // Select the element with the .has-menu class
        const enrollElement = document.querySelector('.action-link');

        // Add the click event listener to toggle the .no-display class when the menu element is clicked
        enrollElement.addEventListener('click', function(event) {
            var enrollSubNav = document.querySelector('.modal-footer .sub-nav-list');

            // Toggle the .no-display class
            enrollSubNav.classList.toggle('no-display');

            // If the .no-display class is removed (meaning the element is displayed), listen for clicks outside the targetElement
            if (!enrollSubNav.classList.contains('no-display')) {
                document.addEventListener('click', outsideClickListener);
            }
        });

        // Function to check for clicks outside the target element
        function outsideClickListener(event) {
            const enrollSubNav = document.querySelector('.modal-footer .sub-nav-list');
            
            // Check if the click happened outside the targetElement and the menuElement
            if (!enrollSubNav.contains(event.target) && !enrollElement.contains(event.target)) {
                // Add the .no-display class back
                enrollSubNav.classList.add('no-display');
                
                // Remove this event listener after the .no-display class is added
                document.removeEventListener('click', outsideClickListener);
            }
        }
    </script>
</body>
</html>